sudo: required
language: ruby
rvm:
- 2.4.1
cache: bundler
branches:
  only:
  - master
before_install:
- FILE=$(mktemp)
- wget 'https://s3.amazonaws.com/public.localytics/artifacts/cogito/libcogito_0.2.0-1_amd64.deb' -qO $FILE
- sudo dpkg -i $FILE && rm $FILE
script:
- bundle exec rake
- bundle exec rubocop
