sudo: required
language: ruby
rvm:
- 2.3.1
cache: bundler
branches:
  only:
  - master
before_install:
- URL='https://s3.amazonaws.com/public.localytics/artifacts/libcogito_0.0.1-1_amd64.deb'
- FILE=`mktemp`; wget "$URL" -qO $FILE && sudo dpkg -i $FILE; rm $FILE
script:
- bundle exec rake
- bundle exec rubocop
