sudo: required
language: ruby
rvm: 2.6.3
cache: bundler
branches:
  only: master
before_install:
- FILE=$(mktemp)
- wget 'https://github.com/cogito-lang/libcogito/releases/download/v0.2.0/libcogito_0.2.0-1_amd64.deb' -qO $FILE
- sudo dpkg -i $FILE && rm $FILE
- gem update --system
- gem install bundler
script:
- bundle exec rake
- bundle exec rubocop
