name: Main
on: push
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - run: FILE=$(mktemp) && wget 'https://github.com/cogito-lang/libcogito/releases/download/v0.2.0/libcogito_0.2.0-1_amd64.deb' -qO $FILE && sudo dpkg -i $FILE && rm $FILE
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - run: bundle config path vendor/bundle
    - run: bundle install --jobs 4 --retry 3
    - run: bundle exec rubocop --parallel
    - run: bundle exec rake test
      env:
        CI: true
